.gitignore, web/package.json, web/src/pages/login/index.module.scss, web/src/pages/login/index.tsx
=> init login page

web/src/App.tsx, web/src/dtos/route-index/index.ts, web/src/dtos/route-type/index.ts, web/src/pages/home/hook.ts, web/src/pages/home/index.module.scss, web/src/pages/home/index.tsx, web/src/pages/main/hook.ts, web/src/pages/main/index.module.scss, web/src/pages/main/index.tsx, web/src/pages/user/index.module.scss, web/src/pages/user/index.tsx, web/src/router/elementRoute.tsx
Create user management page
Close #12
=> Create user page

web/Dockerfile
=> Add DockerFile

web/src/uilts/convert-base64/demo.tsx, web/src/uilts/convert-base64/index.ts
add convert base64 method
Close #21
=> add convert base64 method

web/package.json, web/src/dtos/enterprise/index.ts, web/src/pages/enterprise/components/select-target-dialog/hook.ts, web/src/pages/enterprise/components/select-target-dialog/index.tsx, web/src/pages/enterprise/components/send-message/hook.tsx, web/src/pages/enterprise/components/send-message/index.tsx
Optimization send message component data structure and UI
Close #23
=> Optimization send message component data structure and UI

web/package.json, web/src/App.tsx, web/src/AppHook.ts, web/src/api/email/index.ts, web/src/dtos/email/index.ts, web/src/pages/email/hook.ts, web/src/pages/email/index.module.scss, web/src/pages/email/index.tsx, web/src/router/elementRoute.tsx, web/src/uilts/wangEditor/index.ts
=> add send email page

web/public/index.html, web/src/dtos/enterprise/index.ts, web/src/pages/notification/hook.ts, web/src/pages/notification/index.module.scss, web/src/pages/notification/index.tsx
显示发送记录中的已删除的job颜色以及修改public中的链接描述
Close #29
=> enhance send job record

web/src/api/enterprise/index.ts, web/src/dtos/enterprise/index.ts, web/src/pages/email/hook.ts, web/src/pages/email/index.module.scss, web/src/pages/email/index.tsx, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-target-dialog/hook.ts, web/src/pages/enterprise/components/select-target-dialog/index.tsx, web/src/pages/login/hook.ts, web/src/pages/notification/index.tsx
optimize department list structure
Close #33
=> optimize department list structure

web/src/pages/enterprise/components/select-target-dialog/index.tsx
=> enhance fuzzy query

web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.module.scss, web/src/pages/enterprise/components/select-content/index.tsx
=> add file mark

web/src/api/enterprise/index.ts, web/src/api/http-client.tsx, web/src/dtos/enterprise/index.ts, web/src/pages/email/hook.ts, web/src/pages/email/index.tsx, web/src/pages/enterprise/components/date-selector/index.tsx, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.tsx, web/src/pages/enterprise/components/select-target-dialog/hook.ts, web/src/pages/enterprise/components/select-target-dialog/index.tsx, web/src/pages/enterprise/components/time-selector/index.tsx
add create group component
Close #35
=> add create group component

web/src/dtos/enterprise/index.ts, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.tsx, web/src/pages/enterprise/components/select-target-dialog/hook.ts, web/src/pages/enterprise/components/select-target-dialog/index.tsx, web/src/pages/notification/hook.ts, web/src/pages/notification/index.tsx, web/src/uilts/parameter-judgment/index.tsx
optimization group component
Close #41
=> optimization group component

web/src/pages/enterprise/components/select-target-dialog/index.tsx
=> modify dialog ui

web/src/App.test.tsx
=> test for ci

web/src/pages/enterprise/components/select-target-dialog/hook.ts, web/src/pages/enterprise/components/select-target-dialog/index.tsx
Modify the order of the dialog type list
Close #47
=> Modify the order of the dialog type list

web/src/pages/enterprise/components/select-target-dialog/index.tsx
add search to group selector
Close #49
=> add search to group selector

web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.tsx, web/src/pages/enterprise/components/select-content/props.ts, web/src/pages/enterprise/components/send-message/hook.tsx, web/src/pages/enterprise/components/send-message/index.tsx
add input for selected target
Close #51
=> add input for selected target

web/src/pages/enterprise/components/select-content/index.tsx
=> version increment

web/src/pages/enterprise/components/select-content/index.tsx
=> fix clear data bug

web/src/pages/enterprise/components/select-content/hook.ts
fix file upload accept
Close #57
=> fix file upload accept

web/src/dtos/enterprise/index.ts, web/src/pages/notification/hook.ts, web/src/pages/notification/index.tsx
=> enhance send record fields display and add delete record operating restrictions

web/package.json, web/src/pages/enterprise/components/time-selector/index.tsx
=> fix echo time bug

web/src/api/enterprise/index.ts, web/src/api/http-client.tsx, web/src/dtos/enterprise/index.ts, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.tsx, web/src/uilts/parameter-judgment/index.tsx
enhance graphic type content
Close #64
=> enhance graphic type content

web/src/dtos/enterprise/index.ts, web/src/dtos/send-message-job/index.ts, web/src/pages/email/hook.ts, web/src/pages/email/index.tsx, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.tsx, web/src/pages/enterprise/components/send-message/hook.tsx, web/src/pages/enterprise/components/time-selector/index.tsx, web/src/pages/notification/ components/send-record/index.module.scss, web/src/pages/notification/ components/send-record/index.tsx, web/src/uilts/parameter-judgment/index.tsx
fix exception send record style and timezone and endDate
Close #68
=> fix exception send record style and timezone and endDate

web/src/index.module.scss, web/src/pages/enterprise/components/select-content/index.tsx
fix input label flashing
Close #70
=> fix input label flashing

web/src/dtos/enterprise/index.ts, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.module.scss, web/src/pages/enterprise/components/select-content/index.tsx, web/src/pages/enterprise/components/send-message/index.module.scss, web/src/pages/enterprise/index.module.scss, web/src/pages/home/index.module.scss, web/src/pages/notification/hook.ts
fix send record content column display
Close #75
=> fix send record content column display

web/src/dtos/enterprise/index.ts, web/src/pages/notification/hook.ts, web/src/pages/notification/index.tsx
fix send record error background
Close #76
=> fix send record error background

web/src/pages/notification/hook.ts
enhance send record history compatible
Close #78
=> enhance send record history compatible

web/src/dtos/enterprise/index.ts, web/src/index.module.scss, web/src/pages/email/hook.ts, web/src/pages/email/index.module.scss, web/src/pages/email/index.tsx, web/src/pages/notification/hook.ts
fix email send format and send with picture
Close #72
=> fix email send format and send with picture

web/src/pages/enterprise/components/date-selector/index.tsx, web/src/pages/enterprise/components/time-selector/index.tsx
=> cancel time format

web/src/uilts/parameter-judgment/index.tsx
=> fixed time contrast

web/src/dtos/enterprise/index.ts, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.tsx, web/src/pages/enterprise/components/select-target-dialog/hook.ts, web/src/pages/enterprise/components/select-target-dialog/index.tsx, web/src/uilts/parameter-judgment/index.tsx
Distinguish between confirm and cancel
Close #88
=> Distinguish between confirm and cancel

web/src/dtos/enterprise/index.ts, web/src/pages/email/hook.ts, web/src/pages/email/index.module.scss, web/src/pages/email/index.tsx, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-target-dialog/index.tsx, web/src/pages/notification/hook.ts, web/src/pages/notification/index.tsx
add setting to email record and fix group name do not show on record
Close #90
=> add setting to email record and fix group name do not show on record

web/src/dtos/send-message-job/index.ts, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.tsx
change name of file type
Close #92
=> change name of file type

web/package.json, web/src/pages/email/hook.ts, web/src/pages/email/index.module.scss, web/src/pages/email/index.tsx, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/time-selector/index.tsx, web/src/pages/notification/ components/send-record/index.tsx, web/src/pages/notification/ components/send-record/props.ts, web/src/pages/notification/hook.ts, web/src/pages/notification/index.tsx, web/src/pages/user/component/add-aipkey/index.tsx, web/src/pages/user/component/registration/index.tsx, web/src/pages/user/index.tsx, web/src/uilts/parameter-judgment/index.tsx
=> fix email send bugs

web/src/pages/email/hook.ts
fix value of time passing
Close #96
=> Fix value of time passing

web/src/pages/email/hook.ts
fix show copy to state set boolean
Close #98
=> fix show copy to state set boolean

web/src/dtos/enterprise/index.ts, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.tsx, web/src/pages/enterprise/components/select-target-dialog/index.tsx, web/src/pages/notification/hook.ts
add display field for none selected and hide label selector
Close #100
=> add display field for none selected

web/package.json
add label to minute selector
Close #102
=> add label to minute selector

web/src/pages/email/hook.ts, web/src/pages/email/index.module.scss, web/src/pages/email/index.tsx
change time selector
Close #104
=> change time selector

web/src/pages/user/component/add-aipkey/hook.ts, web/src/pages/user/component/add-aipkey/index.module.scss, web/src/pages/user/component/add-aipkey/index.tsx, web/src/pages/user/component/registration/hook.ts, web/src/pages/user/component/registration/index.module.scss, web/src/pages/user/component/registration/index.tsx, web/src/pages/user/hook.ts, web/src/pages/user/index.tsx
优化用户管理页面的UI和修复添加apikey逻辑问题
Close #108
=> enhance user management

web/package.json, web/src/api/enterprise/index.ts, web/src/dtos/enterprise/index.ts, web/src/pages/email/index.module.scss, web/src/pages/email/index.tsx, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.module.scss, web/src/pages/enterprise/components/select-content/index.tsx, web/src/pages/enterprise/components/select-target-dialog/hook.ts, web/src/pages/enterprise/components/select-target-dialog/index.tsx
Add mention group member
Close #114
=> Add mention group member

web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.tsx
Fix the showing of corp and app selector
Close #118
=> Fix the showing of corp and app selector

web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.tsx, web/src/pages/enterprise/components/select-content/props.ts, web/src/pages/enterprise/components/send-message/hook.tsx, web/src/pages/enterprise/components/send-message/index.tsx
change selector showing
Close #122
=> change selector showing

web/src/pages/enterprise/components/select-content/hook.ts
fix tree view structure
Close #124
=> fix tree view structure

web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-target-dialog/index.tsx
=> fixed tree view UI

web/src/api/enterprise/index.ts, web/src/pages/enterprise/components/select-target-dialog/hook.ts, web/src/pages/enterprise/components/select-target-dialog/index.tsx
enhance group search
Close #130
=> enhance group search

web/src/dtos/enterprise/index.ts, web/src/pages/notification/hook.ts, web/src/pages/notification/index.tsx, web/src/pages/request/component/body/hook.ts, web/src/pages/request/component/body/index.module.scss, web/src/pages/request/component/body/index.tsx, web/src/pages/request/component/body/props.ts, web/src/pages/request/hook.ts, web/src/pages/request/index.module.scss, web/src/pages/request/index.tsx, web/src/router/elementRoute.tsx
=> send request page ui and function develop

web/src/pages/enterprise/components/date-selector/index.tsx
fix date select logic 
Close #136
=> Fix date select logic 

web/package.json
=> Fix mudule

web/src/dtos/app-manager/index.ts, web/src/dtos/enterprise/index.ts, web/src/pages/app-manager/component/corp-app-dialog/hook.ts, web/src/pages/app-manager/component/corp-app-dialog/index.tsx, web/src/pages/app-manager/hook.ts
enhance add and modified enterprise ui
Close #142
=> Enhance add and modified enterprise ui

web/src/api/http-client.tsx, web/src/pages/app-manager/component/corp-app-dialog/hook.ts, web/src/pages/app-manager/component/corp-app-dialog/index.tsx
enhance add and modify apps ui
Close #144
=> Enhance add and modify apps ui

web/package.json, web/src/pages/home/index.tsx, web/src/pages/main/index.tsx
enhance home page navigation bar UI
Close #146
=> Enhance home page navigation bar UI

web/src/pages/home/index.module.scss
enhance home page ui
Close #148
=> Enhance home page ui

web/src/dtos/enterprise/index.ts, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.module.scss, web/src/pages/enterprise/components/select-content/index.tsx, web/src/pages/enterprise/components/select-target-dialog/hook.ts, web/src/pages/enterprise/components/select-target-dialog/index.tsx, web/src/pages/enterprise/components/send-message/index.module.scss, web/src/pages/enterprise/components/send-message/index.tsx, web/src/pages/home/index.module.scss, web/src/uilts/parameter-judgment/index.tsx
Fix white screen bug
Close #150
=> Fix white screen bug

web/src/pages/enterprise/components/select-content/hook.ts
Fix data lost problem of flatten list for send target selector
修复搜索用户框数据丢失问题
Close #152
=> Fix data lost problem of flatten list for send target selector

web/src/pages/enterprise/components/select-content/hook.ts
Fix select send target problem
Close #154
=> Fix select send target problem

web/src/api/meeting-seetings/index.tsx, web/src/dtos/meeting-seetings/index.ts, web/src/pages/meeting-list/components/meeting-settings/component/settingsDialog/hook.ts, web/src/pages/meeting-list/components/meeting-settings/component/settingsDialog/index.tsx, web/src/pages/meeting-list/components/meeting-settings/hook.ts, web/src/pages/meeting-list/components/meeting-settings/index.tsx, web/src/pages/meeting-list/hook.ts, web/src/pages/meeting-list/index.tsx
meetingRecordType   录制类型
meetingSummaryDistributionEnabled   是否发送会议总结给参会人
enableCloudRecordSummary   是否开启会议总结
更换会议详情数据为会议列表的数据
Close #156
=> Meeting setting add new field

web/src/pages/enterprise/components/select-target-dialog/hook.ts, web/src/pages/meeting-list/components/meeting-settings/component/add-participant-dialog/hook.ts, web/src/pages/meeting-list/components/meeting-settings/hook.ts, web/src/pages/meeting-list/components/meeting-settings/index.tsx
=> Fix search bug and deselect group data

web/src/pages/meeting-list/components/meeting-settings/component/add-participant-dialog/hook.ts, web/src/pages/meeting-list/components/meeting-settings/component/add-participant-dialog/index.tsx, web/src/pages/meeting-list/components/meeting-settings/component/settingsDialog/hook.ts, web/src/pages/meeting-list/components/meeting-settings/hook.ts
=> Fix echo conference data bug

web/src/components/treeViewSelector/hook.ts, web/src/components/treeViewSelector/props.ts, web/src/dtos/meeting-seetings/index.ts, web/src/hooks/deptUserData/index.ts, web/src/pages/enterprise/components/select-content/hook.ts, web/src/pages/enterprise/components/select-content/index.module.scss, web/src/pages/enterprise/components/select-content/index.tsx, web/src/pages/enterprise/components/select-target-dialog/hook.ts, web/src/pages/meeting-list/components/meeting-settings/component/add-participant-dialog/hook.ts, web/src/pages/meeting-list/components/meeting-settings/component/add-participant-dialog/index.tsx, web/src/pages/meeting-list/components/meeting-settings/component/add-participant-dialog/props.ts, web/src/pages/meeting-list/components/meeting-settings/component/settingsDialog/hook.ts, web/src/pages/meeting-list/components/meeting-settings/component/settingsDialog/index.tsx, web/src/pages/meeting-list/components/meeting-settings/hook.ts, web/src/pages/meeting-list/components/meeting-settings/index.tsx
替换选择企业成员组件为新增的公共组件
Close  #166
=> Fix introduce  components and optimize logic

web/src/components/treeViewSelector/index.tsx, web/src/pages/enterprise/components/select-target-dialog/index.tsx, web/src/pages/meeting-list/components/meeting-settings/component/add-participant-dialog/index.tsx
=> Fix autocomplete onchange bug

web/src/components/treeViewSelector/hook.ts, web/src/components/treeViewSelector/index.module.scss, web/src/components/treeViewSelector/index.tsx, web/src/pages/enterprise/components/select-target-dialog/index.tsx
=> Optimize personnel popup ui

web/package.json, web/src/pages/role-perimission/components/user-list/components/add-users-model/hook.ts, web/src/pages/role-perimission/components/user-list/components/add-users-model/index.module.scss, web/src/pages/role-perimission/components/user-list/components/add-users-model/index.tsx, web/src/pages/role-perimission/components/user-list/components/add-users-model/props.ts
=> Add role permission assign tree

web/src/pages/role-perimission/components/user-list/components/add-users-model/hook.ts, web/src/pages/role-perimission/components/user-list/components/add-users-model/index.module.scss, web/src/pages/role-perimission/components/user-list/components/add-users-model/index.tsx
新增删除已选的内容以及优化交互
https://github.com/sj-distributor/PostBoy.Web/assets/139139520/e76d5861-32d2-49bf-b2d3-6eceb5d13ace
Close #190
=> Add assignment selected item delete 

web/src/dtos/role/index.ts, web/src/pages/role-perimission/components/role-from/hook.ts, web/src/pages/role-perimission/components/role-from/index.tsx, web/src/pages/role-perimission/components/role-from/props.ts, web/src/pages/role-perimission/components/role-permissions/index.tsx
=> Data permission tree checkbox in add new role

web/src/components/treeViewSelector/index.tsx, web/src/hooks/deptUserData/index.ts, web/src/pages/main/index.module.scss, web/src/router/elementRoute.tsx
=> Fix tree bug

web/src/pages/enterprise/components/select-content/hook.ts
=> Fix app select component

web/package.json, web/src/pages/role-perimission/index.tsx
=> Notistack plug-in  access

web/src/pages/role-perimission/components/role-from/departments.json, web/src/pages/role-perimission/components/role-from/hook.ts, web/src/pages/role-perimission/components/role-from/index.tsx, web/src/pages/role-perimission/components/role-from/props.ts
=> Docking roles department tree

web/public/index.html, web/src/api/email/index.ts, web/src/api/http-client.tsx, web/src/api/login/index.tsx, web/src/api/user-management/index.tsx, web/src/dtos/user-management/index.ts, web/src/pages/user/component/add-aipkey/hook.ts, web/src/pages/user/component/add-aipkey/index.tsx, web/src/pages/user/component/registration/hook.ts, web/src/pages/user/component/registration/index.tsx, web/src/pages/user/hook.ts, web/src/pages/user/index.module.scss, web/src/pages/user/index.tsx
=> Docking user manage api update

web/src/dtos/role-user-permissions/index.ts
=> update role name

web/src/pages/role-perimission/components/role-from/index.tsx, web/src/pages/role-perimission/components/role-permissions/hook.ts
=> Update edit rote

web/src/pages/meeting-list/components/meeting-settings/index.tsx
=> Fixed ci type error

web/src/components/modal/modal.tsx, web/src/pages/role-perimission/components/add-users-model/index.tsx, web/src/pages/role-perimission/components/tree-select/index.tsx
=> Fixed modalbox type error

web/src/pages/role-perimission/components/tree-select/hook.ts, web/src/pages/role-perimission/components/tree-select/index.tsx, web/src/pages/user/index.tsx, web/src/router/elementRoute.tsx
=> Fixed optimize code

web/package.json, web/src/api/role-user-permissions/index.ts, web/src/dtos/role-user-permissions/index.ts, web/src/pages/role-perimission/components/add-users-model/hook.ts, web/src/pages/role-perimission/components/user-list/hook.ts
=> Fixed tree already select bug

web/package.json, web/src/pages/home/hook.ts
=> Fixed ci version optimize

web/src/api/role-user-permissions/index.ts, web/src/dtos/role-user-permissions/index.ts, web/src/pages/role-perimission/components/role-from/hook.ts, web/src/pages/role-perimission/components/role-permissions/hook.ts, web/src/pages/role-perimission/components/role-permissions/index.tsx
=> Fixed user role logic optimize 

web/Dockerfile, web/src/api/enterprise/index.ts, web/src/dtos/enterprise/index.ts, web/src/pages/enterprise/components/select-content/hook.ts
=> Docking message file api

web/src/hooks/deptUserData/index.ts, web/src/pages/meeting-list/components/meeting-settings/hook.ts
Close #254 
优化获取周期会议参会人信息信息不全问题
=> Fixed get new acquisition fo attendees

web/src/api/http-client.tsx, web/src/api/white-list/index.ts, web/src/dtos/white-list/index.ts, web/src/hooks/authProvider/index.tsx, web/src/pages/main/index.module.scss, web/src/pages/main/index.tsx, web/src/pages/meeting-white-list/hook.ts, web/src/pages/meeting-white-list/index.module.scss, web/src/pages/meeting-white-list/index.tsx, web/src/pages/meeting-white-list/props.ts, web/src/pages/meeting/index.module.scss, web/src/pages/meeting/index.tsx, web/src/router/elementRoute.tsx
=> Add meeting summary white list page
